version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip install -r requirements.txt  # Install dependencies
  pre_build:
    commands:
      - echo "Running Unit Tests"
      - python -m unittest discover -s tests -p "test_app.py"
  build:
    commands:
      - echo "Building Docker image"
      - $(aws ecr get-login-password --region us-east-1) | docker login --username AWS --password-stdin 654654369899.dkr.ecr.us-east-1.amazonaws.com
      - docker build -t <your-ecr-repo-name>:latest .
      - docker tag <your-ecr-repo-name>:latest 654654369899.dkr.ecr.us-east-1.amazonaws.com/<your-ecr-repo-name>:latest
  post_build:
    commands:
      - echo "Pushing Docker image to ECR"
      - docker push 654654369899.dkr.ecr.us-east-1.amazonaws.com/<your-ecr-repo-name>:latest
      - echo "Build completed"
artifacts:
  files:
    - '**/*'