"""Re-initializing migrations

Revision ID: 320a5e76e1e0
Revises: 2cdc1415e7a0
Create Date: 2025-01-30 17:35:09.671280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '320a5e76e1e0'
down_revision = '2cdc1415e7a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=700),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=700),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)

    # ### end Alembic commands ###
